"""
Pydantic Schemas — schemas.py
==============================
The bouncer at the door — validates data before it reaches the database.

WHAT IT DOES:
  Defines the SHAPE and RULES for data coming in (requests) and going out (responses).
  If someone sends invalid data (e.g., priority="super-duper"), Pydantic rejects it
  with a clear error message BEFORE it ever touches the database.

models.py vs schemas.py:
  models.py  → defines what the DATABASE looks like (columns, types)
  schemas.py → defines what the API ACCEPTS and RETURNS (validation, serialization)

  Think of it like this:
    models.py  = the filing cabinet (where data is stored)
    schemas.py = the intake form (what data is allowed in / what you get back)

WHY SEPARATE?
  You might want to accept different data than what's in the database.
  For example:
    - TaskCreate only needs description + priority (the database adds id, timestamps)
    - TaskUpdate makes everything optional (you might only update the priority)
    - TaskResponse includes everything (id, timestamps, etc.) for the frontend

KEY CONCEPTS:
  BaseModel     → Pydantic's base class; validates data automatically
  str | None    → Python 3.10+ syntax meaning "string OR null"
  model_config  → tells Pydantic how to convert SQLAlchemy objects to JSON
"""

# BaseModel — the parent class for all Pydantic schemas (handles validation)
from pydantic import BaseModel

# datetime — for timestamp fields in responses
from datetime import datetime

# Enum — for restricting priority to specific values
from enum import Enum


# ============================================================
# PRIORITY ENUM
# ============================================================
# Restricts priority to exactly three values: "low", "normal", "high"
# If someone sends priority="urgent", Pydantic will reject it.
# str, Enum → inherits from both str AND Enum, so it serializes as a string in JSON
class PriorityEnum(str, Enum):
    low = "low"
    normal = "normal"
    high = "high"


# ============================================================
# REQUEST SCHEMAS (what the frontend SENDS to the backend)
# ============================================================

class TaskCreate(BaseModel):
    """
    Schema for CREATING a new task.
    This is the data the frontend sends when adding a task.

    Required: description (what the task is)
    Optional: priority (defaults to "normal" if not specified)

    Example request body:
      {"description": "Buy groceries", "priority": "high"}
      {"description": "Call mom"}  ← priority defaults to "normal"
    """
    description: str                              # Required — what the task is
    priority: PriorityEnum = PriorityEnum.normal  # Optional — defaults to "normal"


class TaskUpdate(BaseModel):
    """
    Schema for UPDATING an existing task.
    All fields are optional — you only send what you want to change.

    Example request bodies:
      {"completed": true}                      ← just mark it done
      {"description": "Buy milk instead"}      ← just change the description
      {"priority": "high", "completed": false}  ← change priority and un-complete it
    """
    description: str | None = None          # Optional — new description
    priority: PriorityEnum | None = None    # Optional — new priority
    completed: bool | None = None           # Optional — mark as done/undone


# ============================================================
# RESPONSE SCHEMA (what the backend SENDS BACK to the frontend)
# ============================================================

class TaskResponse(BaseModel):
    """
    Schema for RETURNING task data to the frontend.
    Includes all fields — the frontend needs the full picture.

    Example response:
      {
        "id": 1,
        "description": "Buy groceries",
        "priority": "high",
        "completed": false,
        "created_at": "2025-12-10T15:30:00",
        "completed_at": null
      }
    """
    id: int                          # Task ID (auto-generated by the database)
    description: str                 # Task description
    priority: PriorityEnum           # Task priority (low/normal/high)
    completed: bool                  # Is the task done?
    created_at: datetime             # When was it created?
    completed_at: datetime | None    # When was it completed? (null if not done)

    # from_attributes=True tells Pydantic:
    # "You can read data directly from SQLAlchemy model attributes (like task.description)"
    # Without this, Pydantic would only accept dictionaries, not ORM objects.
    model_config = {"from_attributes": True}
